#
# Makefile for the video capture/playback device drivers.
#
obj-y				+= avp/
obj-$(CONFIG_TEGRA_CAMERA)	+= tegra_camera.o

obj-y				+= imx072_main.o
obj-y				+= imx072_eeprom.o
obj-y				+= dw9716.o
obj-y				+= s5k5bafx.o
obj-y				+= s5k5bafx_setting_value.o
obj-$(CONFIG_VIDEO_OV5650)	+= ov5650.o
obj-$(CONFIG_VIDEO_OV2710)	+= ov2710.o

